name: twh_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.7+4
  image_picker_web: ^3.0.0+1
  firebase_core: ^2.11.0
  firebase_storage: ^11.1.2
  firebase_messaging: ^14.6.1
  cached_network_image: ^3.2.1
  shared_preferences: ^2.1.1
  flutter_svg: ^1.1.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

