// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3sA2gjHmiuxGAIA6ikFD9ILJHsB1NV8',
    appId: '1:482125193930:web:ef7823520ecacf8d404a33',
    messagingSenderId: '482125193930',
    projectId: 'the-wagon-house-9314a',
    authDomain: 'the-wagon-house-9314a.firebaseapp.com',
    storageBucket: 'the-wagon-house-9314a.appspot.com',
    measurementId: 'G-JWDKWEHC6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLyxjxndOqNLVeaHwhPEVpLsloJf6jHU',
    appId: '1:482125193930:android:678931674b97c052404a33',
    messagingSenderId: '482125193930',
    projectId: 'the-wagon-house-9314a',
    storageBucket: 'the-wagon-house-9314a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0qlpuKrUAkpewqv1U56FbpXNBJyxeu4',
    appId: '1:482125193930:ios:4d1729aab25ca9a2404a33',
    messagingSenderId: '482125193930',
    projectId: 'the-wagon-house-9314a',
    storageBucket: 'the-wagon-house-9314a.appspot.com',
    iosClientId: '482125193930-soqn3dvtmh5p2hqsecb5k3rlaq7it0v1.apps.googleusercontent.com',
    iosBundleId: 'com.twh.twhAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0qlpuKrUAkpewqv1U56FbpXNBJyxeu4',
    appId: '1:482125193930:ios:4d1729aab25ca9a2404a33',
    messagingSenderId: '482125193930',
    projectId: 'the-wagon-house-9314a',
    storageBucket: 'the-wagon-house-9314a.appspot.com',
    iosClientId: '482125193930-soqn3dvtmh5p2hqsecb5k3rlaq7it0v1.apps.googleusercontent.com',
    iosBundleId: 'com.twh.twhAdmin',
  );
}
